### ISSUE TITLE
Create a docker image + circleci builder

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/megaphone#12]
Setup the necessary Docker file and a rust building environment on circleci.

Not sure it's totally necessary but https://github.com/emk/rust-musl-builder is available for building very portable static rust binaries, which might be helpful down the line for deploying into generic linux Docker images.

**Comment by mostlygeek** [comment]
[Dockerflow](https://github.com/mozilla/dockerflow)? :)

**Comment by pjenvey** [comment]
> Dockerflow? :)

Yup and good timing, @mostlygeek, I was about to bug you to create https://hub.docker.com/u/mozilla/megaphone/ and get its credentials into https://circleci.com/gh/mozilla-services/megaphone

**Comment by mostlygeek** [comment]
@oremj could you set up the dockerhub / circleci stuff?

**Comment by oremj** [comment]
The dockerhub environment variables are all set up.
