### ISSUE TITLE
MVP for megaphone app

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/megaphone#4]
- [x] Initial prototype [PR #8](https://github.com/mozilla-services/megaphone/pull/8)
- [x] [Auth validation](https://github.com/mozilla-services/megaphone/issues/7)
- [x] [Docker setup](https://github.com/mozilla-services/megaphone/issues/12) 
- [x] [Setup AWS deployment](https://github.com/mozilla-services/megaphone/issues/10)

**Comment by bbangert** [comment]
The MVP will implement the RESTful API call to handle POST's from the broadcaster, as well as GET's from the connection nodes that have all the broadcast's and versions. It will also publish changes to the AWS SNS topic.

**Comment by pjenvey** [comment]
Updated these old targets:

Integration with AWS services (SNS, SQS, DDB, etc.)
Auth validation
Version publication on service update

**Comment by pjenvey** [comment]
good to go
