### ISSUE TITLE
Attempt to sync errno codes w/ pushbox

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/megaphone#50]
Probably won't match exactly but it's worth an attempt to keep them in sync

**Comment by bbangert** [comment]
I think the errno is already the subset, since 'status' is the classification (200, 400, etc), no?

In that case errno is always app-specific, but we mandate that 'status' is the main dewey classifier portion.

**Comment by pjenvey** [comment]
Yea -- I just going to give this a cursory look but it's just not that important enough, closing
