### ISSUE TITLE
Upgrade to Rocket 0.4.5

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/megaphone#84]

**Comment by jrconlin** [comment]
OBE.

rocket updated as part of https://github.com/mozilla-services/megaphone/pull/85

**Comment by tublitzed** [comment]
@jrconlin - looks like we're still on [0.4.2](https://github.com/mozilla-services/megaphone/blob/master/Cargo.toml#L17)?

**Comment by jrconlin** [comment]
Ah, heh. Apparently I had rounded up locally and not pushed.
